In [31]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [32]:
df = sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

predict what is the time?

In [33]:
df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [35]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

since time is norma;l variable, then we will use label encoder


In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
encoder = LabelEncoder()
df['time'] = encoder.fit_transform(df['time'])

In [38]:
df

total_bill   tip     sex smoker   day  time  size
0         16.99  1.01  Female     No   Sun     0     2
1         10.34  1.66    Male     No   Sun     0     3
2         21.01  3.50    Male     No   Sun     0     3
3         23.68  3.31    Male     No   Sun     0     2
4         24.59  3.61  Female     No   Sun     0     4
..          ...   ...     ...    ...   ...   ...   ...
239       29.03  5.92    Male     No   Sat     0     3
240       27.18  2.00  Female    Yes   Sat     0     2
241       22.67  2.00    Male    Yes   Sat     0     2
242       17.82  1.75    Male     No   Sat     0     2
243       18.78  3.00  Female     No  Thur     0     2

[244 rows x 7 columns]

In [39]:
x = df.drop('time',axis = 1)

In [40]:
y = df['time']

In [41]:
df.time.unique()

array([0, 1])

In [42]:
x

total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [43]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int64

In [44]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 1)

In [45]:
x_train

total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
154       19.77  2.00    Male     No   Sun     4
167       31.71  4.50    Male     No   Sun     4
110       14.00  3.00    Male     No   Sat     2
225       16.27  2.50  Female    Yes   Fri     2
..          ...   ...     ...    ...   ...   ...
137       14.15  2.00  Female     No  Thur     2
72        26.86  3.14  Female    Yes   Sat     2
140       17.47  3.50  Female     No  Thur     2
235       10.07  1.25    Male     No   Sat     2
37        16.93  3.07  Female     No   Sat     3

[195 rows x 6 columns]

In [46]:
x_test

total_bill    tip     sex smoker   day  size
67         3.07   1.00  Female    Yes   Sat     1
243       18.78   3.00  Female     No  Thur     2
206       26.59   3.41    Male    Yes   Sat     3
122       14.26   2.50    Male     No  Thur     2
89        21.16   3.00    Male     No  Thur     2
218        7.74   1.44    Male    Yes   Sat     2
58        11.24   1.76    Male    Yes   Sat     2
186       20.90   3.50  Female    Yes   Sun     3
177       14.48   2.00    Male    Yes   Sun     2
4         24.59   3.61  Female     No   Sun     4
220       12.16   2.20    Male    Yes   Fri     2
226       10.09   2.00  Female    Yes   Fri     2
116       29.93   5.07    Male     No   Sun     4
107       25.21   4.29    Male    Yes   Sat     2
170       50.81  10.00    Male    Yes   Sat     3
241       22.67   2.00    Male    Yes   Sat     2
181       23.33   5.65    Male    Yes   Sun     2
51        10.29   2.60  Female     No   Sun     2
27        12.69   2.00    Male     No   Sat     2
240       27.18   2.00  Female    Yes   Sat     2
219       30.14   3.09  Female    Yes   Sat     4
34        17.78   3.27    Male     No   Sat     2
93        16.32   4.30  Female    Yes   Fri     2
183       23.17   6.50    Male    Yes   Sun     4
118       12.43   1.80  Female     No  Thur     2
117       10.65   1.50  Female     No  Thur     2
106       20.49   4.06    Male    Yes   Sat     2
73        25.28   5.00  Female    Yes   Sat     2
38        18.69   2.31    Male     No   Sat     3
210       30.06   2.00    Male    Yes   Sat     3
202       13.00   2.00  Female    Yes  Thur     2
44        30.40   5.60    Male     No   Sun     4
62        11.02   1.98    Male    Yes   Sat     2
238       35.83   4.67  Female     No   Sat     3
85        34.83   5.17  Female     No  Thur     4
224       13.42   1.58    Male    Yes   Fri     2
39        31.27   5.00    Male     No   Sat     3
31        18.35   2.50    Male     No   Sat     4
18        16.97   3.50  Female     No   Sun     3
132       11.17   1.50  Female     No  Thur     2
119       24.08   2.92  Female     No  Thur     4
19        20.65   3.35    Male     No   Sat     3
91        22.49   3.50    Male     No   Fri     2
69        15.01   2.09    Male    Yes   Sat     2
33        20.69   2.45  Female     No   Sat     4
90        28.97   3.00    Male    Yes   Fri     2
35        24.06   3.60    Male     No   Sat     3
11        35.26   5.00  Female     No   Sun     4
29        19.65   3.00  Female     No   Sat     2

In [47]:
y_train

0      0
154    0
167    0
110    0
225    1
      ..
137    1
72     0
140    1
235    0
37     0
Name: time, Length: 195, dtype: int64

In [48]:
y_test

67     0
243    0
206    0
122    1
89     1
218    0
58     0
186    0
177    0
4      0
220    1
226    1
116    0
107    0
170    0
241    0
181    0
51     0
27     0
240    0
219    0
34     0
93     0
183    0
118    1
117    1
106    0
73     0
38     0
210    0
202    1
44     0
62     0
238    0
85     1
224    1
39     0
31     0
18     0
132    1
119    1
19     0
91     0
69     0
33     0
90     0
35     0
11     0
29     0
Name: time, dtype: int64

* handeling the missing values,

* data encoding
* feature scalling


In [49]:
from sklearn.impute import SimpleImputer # missing values
from sklearn.preprocessing import OneHotEncoder  # encoding
from sklearn.preprocessing import StandardScaler

In [50]:
from sklearn.pipeline import Pipeline # a sequence of the data tranformer
from sklearn.compose import ColumnTransformer  # group all the pipline steps fro each of the columns

In [51]:
df.sample(1)

total_bill  tip     sex smoker   day  time  size
140       17.47  3.5  Female     No  Thur     1     2

In [52]:
cat_cols = ["sex","smoker","day"]
num_cols = ["total_bill","tip","size"]

In [53]:
num_pipeline=Pipeline(steps= [('imputation',SimpleImputer(strategy = 'median')),('scaling',StandardScaler())])
cat_pipeline=Pipeline(steps= [('imputation',SimpleImputer(strategy = 'most_frequent')),('encoder',OneHotEncoder())])

In [54]:
preprocessor=ColumnTransformer([("num_pipeline",num_pipeline,num_cols),
                   ("cat_pipeline",cat_pipeline,cat_cols)])

In [55]:
x_train = preprocessor.fit_transform(x_train)


In [56]:
x_test = preprocessor.fit_transform(x_test)

In [57]:
x_train

array([[-0.28611937, -1.47443803, -0.57766863, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.02695905, -0.71612531,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.3716196 ,  1.19880579,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.23206267,  0.43283335, -0.57766863, ...,  0.        ,
         0.        ,  1.        ],
       [-1.06543688, -1.29060464, -0.57766863, ...,  1.        ,
         0.        ,  0.        ],
       [-0.29287646,  0.1034652 ,  0.44638031, ...,  1.        ,
         0.        ,  0.        ]])

In [58]:
x_test

array([[-2.00826754, -1.38720268, -1.91558902,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.22900911, -0.15435728, -0.71220617,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.65552356,  0.09837603,  0.49117667,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.74092815, -0.46256863, -0.71220617,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.04054118, -0.15435728, -0.71220617,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-1.47936004, -1.11597669, -0.71220617,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.   

In [59]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression


In [60]:
models = {"support vector classifier": SVC(),
          "DT Classifier": DecisionTreeClassifier(),
          "Log reg": LogisticRegression()}

In [61]:
models

{'support vector classifier': SVC(),
 'DT Classifier': DecisionTreeClassifier(),
 'Log reg': LogisticRegression()}

In [62]:
for i in range(len(models)):
  print(list(models.values())[i])

SVC()
DecisionTreeClassifier()
LogisticRegression()


In [63]:
from sklearn.metrics import accuracy_score
def model_train_eval(x_train,x_test,y_train,y_test,models):
  evaluation = {}
  for i in range(len(models)):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    model_score = accuracy_score(y_test,y_pred)
    evaluation[list(models.keys())[i]] = model_score
  return evaluation

In [64]:
model_train_eval(x_train,x_test,y_train,y_test,models)

{'support vector classifier': 0.9183673469387755,
 'DT Classifier': 0.9183673469387755,
 'Log reg': 0.9183673469387755}

In [65]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf

RandomForestClassifier()

In [66]:
x_train,x_test

(array([[-0.28611937, -1.47443803, -0.57766863, ...,  0.        ,
          1.        ,  0.        ],
        [ 0.02695905, -0.71612531,  1.47042924, ...,  0.        ,
          1.        ,  0.        ],
        [ 1.3716196 ,  1.19880579,  1.47042924, ...,  0.        ,
          1.        ,  0.        ],
        ...,
        [-0.23206267,  0.43283335, -0.57766863, ...,  0.        ,
          0.        ,  1.        ],
        [-1.06543688, -1.29060464, -0.57766863, ...,  1.        ,
          0.        ,  0.        ],
        [-0.29287646,  0.1034652 ,  0.44638031, ...,  1.        ,
          0.        ,  0.        ]]),
 array([[-2.00826754, -1.38720268, -1.91558902,  1.        ,  0.        ,
          0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
          0.        ],
        [-0.22900911, -0.15435728, -0.71220617,  1.        ,  0.        ,
          1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          1.        ],
        [ 0.65552356,  0.098376

In [67]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
params = {'max_depth':[1,2,3,4,5,10,None],
          'n_estimators': [30,40,50,100,200,300],
          'criterion':['gini','entropy']}
params

{'max_depth': [1, 2, 3, 4, 5, 10, None],
 'n_estimators': [30, 40, 50, 100, 200, 300],
 'criterion': ['gini', 'entropy']}

In [68]:
clf=GridSearchCV(rf,param_grid=params,cv = 5, verbose = 3,scoring ='accuracy')
clf

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5, 10, None],
                         'n_estimators': [30, 40, 50, 100, 200, 300]},
             scoring='accuracy', verbose=3)

In [69]:
clf.fit(x_train,y_train)

Fitting 5 folds for each of 84 candidates, totalling 420 fits
[CV 1/5] END criterion=gini, max_depth=1, n_estimators=30;, score=0.744 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=1, n_estimators=30;, score=0.974 total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=1, n_estimators=30;, score=1.000 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=1, n_estimators=30;, score=0.974 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=1, n_estimators=30;, score=1.000 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=1, n_estimators=40;, score=0.923 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=1, n_estimators=40;, score=0.974 total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=1, n_estimators=40;, score=1.000 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=1, n_estimators=40;, score=1.000 total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=1, n_estimators=40;, score=0.897 total time=   0.1s
[CV 1/5] END criterion=gini,

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5, 10, None],
                         'n_estimators': [30, 40, 50, 100, 200, 300]},
             scoring='accuracy', verbose=3)

In [70]:
clf.best_params_

{'criterion': 'gini', 'max_depth': 2, 'n_estimators': 30}

In [71]:
clf.best_score_

np.float64(0.9794871794871796)

In [72]:
best_model = clf.best_estimator_
best_model

RandomForestClassifier(max_depth=2, n_estimators=30)

In [73]:
best_model.fit(x_train,y_train)

RandomForestClassifier(max_depth=2, n_estimators=30)

In [74]:
y_pred = best_model.predict(x_test)
y_pred

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0])

In [75]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95        38
           1       0.89      0.73      0.80        11

    accuracy                           0.92        49
   macro avg       0.91      0.85      0.87        49
weighted avg       0.92      0.92      0.92        49

